var quotes = [
  "Anyone can be confident with a full head of hair. But a confident bald man - there's your diamond in the rough.",
  "I had a wonderful childhood, which is tough because it's hard to adjust to a miserable adulthood.",
  "I tend to stay with the panic. I embrace the panic.",
  "Sometimes you have to wander a bit, and do what you don't want to in order to figure out what it is you're supposed to do.",
  "I've led this empty life for over forty years and now I can pass that heritage on and ensure that the misery will continue for at least one more generation.",
  "All of a sudden I discovered that I'm allergic to caviar. It was the perfect metaphor for my life. When I was only able to afford bad caviar, I could certainly eat my fill of it.",
  "Women love a self-confident bald man.",
  "I don't write shows with dialogue where actors have to memorize dialogue. I write the scenes where we know everything that's going to happen. There's an outline of about seven or eight pages, and then we improvise it.",
  "I think we're all good and bad, but good's not funny. Bad is funny. Suppress the good and let the bad out, and then you can be funny.",
  "When you're not concerned with succeeding, you can work with complete freedom.",
  "The addition of nuts in salad... I always find to be beneficial.",
  "Trying on pants is one of the most humiliating things a man can suffer that doesn't involve a woman.",
  "I don't take on big things. What I do, pretty much, is make the big things small and the small things big.",
  "If you tell the truth about how you're feeling, it becomes funny.",
  "Whenever something good happens to me, it's usually followed by something terrible.",
  "Golf and dating don't mix.",
  "OK, I'm happy. I'm happy. All right? I'm happy.",
  "I don't think anyone really is interested in reading about my emotional state. It's not even interesting to me.",
  "I don't like to be out of my comfort zone, which is about a half an inch wide.",
  "I'm still driving a Prius, yeah.",
  "Every relationship is just so tenuous and precarious.",
  "Once I know people know who I am, it gives me a lot of licence and freedom to behave in ways I wouldn't normally.",
  "It's always good to take something that's happened in your life and make something of it comedically.",
  "I like to be quiet, and let people find me rather than having to shout at them.",
  "The only change I can really see is that I don't have to shop for pants in stores anymore.",
  "Hey, I may loathe myself, but it has nothing to do with the fact that I'm Jewish.",
  "At first, I didn't realize it was gonna be a character. I just thought I was gonna be doing me.",
  "If I wasn't a golfer, I would still be miserable - but not as miserable.",
  "I'm surprised sometimes at how some of my actions are misinterpreted.",
  "I believe in something.",
  "I am not honest.",
  "I don't have many friends.",
  "Fuck you!",
  "I think that what people imagine they're going through is much worse than what they are going through.",
  "Let's not forget, I got divorced.",
  "Anything that's for free, people will take. They don't discriminate.",
  "Most people think I'm immodest.",
  "Anytime I'm involved with anything that's well-received, it's a surprise to me.",
  "You know, I'm really not that bright.",
  "I'm cranky.",
  "I don't like people cleaning my room.",
  "People don't yell nasty things at actors - they let them continue.",
  "I have reservations about everything I do.",
  "I can't stand reading anything that I've said.",
  "I had a job as a paralegal. I drove a cab.",
  "I learned the first night that IHOP's not the place to order fish.",
  "Millions of people are married. I've never picked up a paper and seen a headline that says, Man Gets Married!",
  "I guess I still feel that I'm a comedian; if I had to pick one thing that I feel like I could do, it would be that. That doesn't mean that I like it, but I feel that's what I am.",
  "There's a sense of spontaneity, and no emphasis on jokes in this show. People generally talk the way they talk in life if you were in this particular situation.",
  "I’d rather have the thieves than the neighbors – the thieves don’t impose. Thieves just want your things, neighbors want your time. I’d rather give them things than time.",
  "Can I apologize for the apology?",
  "Most people are completely unaware of their breath. They violate your space, they have no idea that they have halitosis.",
  "The customer is usually a moron and an asshole.",
  "A lie is a gesture, it’s a courtesy, it’s a little respect!",
  "A date is an experience you have with another person that makes you appreciate being alone.",
  "I’m not a person who embraces challenges. I run from challenges. I break world records running from challenges.",
  "Trying on pants is one of the most humiliating things a man can suffer that doesn’t involve a woman.",
  "When you’re not concerned with succeeding, you can work with complete freedom.",
  "A good compromise is when both parties are dissatisfied.",
  "I’m trying to elevate small talk to medium talk.",
  "I don’t like to be out of my comfort zone, which is about a half an inch wide.",
  "I tolerate lactose like I tolerate people.",
  "When I’m in social situations, I always hold onto my glass. It makes me feel comfortable and secure and I don’t have to shake hands.",
  "I just – I can’t stand the sound of the human voice.",
  "It’s always good to take something that’s happened in your life and make something of it comedically.",
  "I’m a jerk, that’s who I am. I’m like everybody else.",
  "I don’t like to have hot food for lunch.",
  "If you tell the truth about how you’re feeling, it becomes funny.",
  "Pretty good. Pretttttttty, pretttttttttty, pretttttty good.",
];
function newQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  document.getElementById("quoteDisplay").innerHTML = quotes[randomNumber];
}

window.onclick = function () {
  document.getElementById("my_audio").play();
  document.body.addEventListener("mousemove", function () {
    audio.play();
  });
};
